j=(-1)**(0.5)
r1=int(input("enter the first real number:"))
i1=int(input("enter the first imaginary number:"))
c1=r1+(j*(i1))
r2=int(input("enter the second real number:"))
i2=int(input("enter the second imaginary number:"))
c2=r2+(j*(i2))
print("the sum of complexs number is:",c1+c2)
print("the multiplication of complex number is:",c1*c2)
