num1=int(input("enter the first number:"))
num2=int(input("enter the second number:"))
print("the sum of two numbers is:",num1+num2)
print("the difference of two numbers is:",num1-num2)
print("the multiplication of two numbers is:",num1*num2)
print("the division of two numbers is:",num1/num2)
